services:
  db:
    image: postgres:17.1-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mysite_dev
      - POSTGRES_PASSWORD=mysite_dev
      - POSTGRES_DB=mysite_dev_db
    networks:
      - backend 
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
        - backend   

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge  